/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import gnu.io.NRSerialPort;
import gnu.io.SerialPortEvent;
import gnu.io.SerialPortEventListener;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author José Quinde
 */
public class VentanaPrincipal extends javax.swing.JFrame implements SerialPortEventListener {

    /**
     * Creates new form VentanaPrincipal
     */
    private NRSerialPort puertoUSB;
    private int valorPot;
    public VentanaPrincipal() {
        initComponents();
        cargarImagenes();
    }

    public void conectar() {
        try {
            puertoUSB = new NRSerialPort("COM5", 9600);
            puertoUSB.connect();
            puertoUSB.notifyOnDataAvailable(true);
            puertoUSB.addEventListener(this);

            txtEstado.setText("Puerto USB Listo...");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void desconectar() {
        if (puertoUSB.isConnected()) {
            puertoUSB.disconnect();
            txtEstado.setText("Puerto USB Desconectado.....");
        }
    }

    public void enviarDato(int valor) {
        try {
            OutputStream escritura = puertoUSB.getOutputStream();
            escritura.write(valor);
            escritura.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

    public void cargarImagenes() {
        ImageIcon apagado = new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/red.png"));
        ImageIcon icono = new ImageIcon(apagado.getImage().getScaledInstance(led1.getWidth(), led1.getHeight(), Image.SCALE_DEFAULT));
        led1.setIcon(icono);
        led2.setIcon(icono);
        led3.setIcon(icono);
        led4.setIcon(icono);
        led5.setIcon(icono);
        led6.setIcon(icono);
        led7.setIcon(icono);

    }

    public void prenderLed(JLabel l) {
        ImageIcon apagado = new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/green.png"));
        ImageIcon icono = new ImageIcon(apagado.getImage().getScaledInstance(led1.getWidth(), led1.getHeight(), Image.SCALE_DEFAULT));
        l.setIcon(icono);
    }
    public void apagarLed(JLabel l) {
        ImageIcon apagado = new ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/red.png"));
        ImageIcon icono = new ImageIcon(apagado.getImage().getScaledInstance(led1.getWidth(), led1.getHeight(), Image.SCALE_DEFAULT));
        l.setIcon(icono);
    }

    public void controlLeds(int valor) {
        if (valor == 1) {
            prenderLed(led1);
        }
        if (valor == 2) {
            prenderLed(led2);
        }
        if (valor == 3) {
            prenderLed(led3);
        }
        if (valor == 4) {
            prenderLed(led4);
        }
        if (valor == 5) {
            prenderLed(led5);
        }
        if (valor == 6) {
            prenderLed(led6);
        }
        if (valor == 7) {
            prenderLed(led7);
        }
        if (valor == 8) {
            apagarLed(led1);
        }
        if (valor == 9) {
            apagarLed(led2);
        }
        if (valor == 10) {
            apagarLed(led3);
        }
        if (valor == 11) {
            apagarLed(led4);
        }
        if (valor == 12) {
            apagarLed(led5);
        }
        if (valor == 13) {
            apagarLed(led6);
        }
        if (valor == 14) {
            apagarLed(led7);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntConectar = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        txtEstado = new javax.swing.JLabel();
        bntLed1 = new javax.swing.JButton();
        btnLed2 = new javax.swing.JButton();
        btnLed3 = new javax.swing.JButton();
        btnLed4 = new javax.swing.JButton();
        btnLed5 = new javax.swing.JButton();
        btnLed6 = new javax.swing.JButton();
        btnLed7 = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        led3 = new javax.swing.JLabel();
        led1 = new javax.swing.JLabel();
        led2 = new javax.swing.JLabel();
        led4 = new javax.swing.JLabel();
        led6 = new javax.swing.JLabel();
        led5 = new javax.swing.JLabel();
        led7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coneccion Arduino");
        setMaximumSize(new java.awt.Dimension(900, 610));
        setMinimumSize(new java.awt.Dimension(900, 610));
        setPreferredSize(new java.awt.Dimension(900, 610));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        bntConectar.setBackground(new java.awt.Color(0, 102, 255));
        bntConectar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bntConectar.setText("Conectar");
        bntConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConectarActionPerformed(evt);
            }
        });
        getContentPane().add(bntConectar);
        bntConectar.setBounds(36, 42, 130, 33);

        btnDesconectar.setBackground(new java.awt.Color(0, 102, 255));
        btnDesconectar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDesconectar.setText("Desconectar");
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesconectar);
        btnDesconectar.setBounds(36, 93, 130, 37);

        txtEstado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(51, 255, 51));
        getContentPane().add(txtEstado);
        txtEstado.setBounds(220, 50, 338, 30);

        bntLed1.setBackground(new java.awt.Color(0, 102, 204));
        bntLed1.setText("LED 1");
        bntLed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLed1ActionPerformed(evt);
            }
        });
        getContentPane().add(bntLed1);
        bntLed1.setBounds(36, 157, 65, 51);

        btnLed2.setBackground(new java.awt.Color(0, 102, 204));
        btnLed2.setText("LED 2");
        btnLed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed2);
        btnLed2.setBounds(36, 215, 65, 51);

        btnLed3.setBackground(new java.awt.Color(0, 102, 204));
        btnLed3.setText("LED 3");
        btnLed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed3);
        btnLed3.setBounds(36, 284, 65, 51);

        btnLed4.setBackground(new java.awt.Color(0, 102, 204));
        btnLed4.setText("LED 4");
        btnLed4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed4);
        btnLed4.setBounds(158, 157, 65, 51);

        btnLed5.setBackground(new java.awt.Color(0, 102, 204));
        btnLed5.setText("LED 5");
        btnLed5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed5);
        btnLed5.setBounds(158, 215, 65, 51);

        btnLed6.setBackground(new java.awt.Color(0, 102, 204));
        btnLed6.setText("LED 6");
        btnLed6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed6);
        btnLed6.setBounds(158, 284, 65, 51);

        btnLed7.setBackground(new java.awt.Color(0, 102, 204));
        btnLed7.setText("LED 7");
        btnLed7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLed7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLed7);
        btnLed7.setBounds(98, 353, 65, 51);

        btnApagar.setBackground(new java.awt.Color(255, 51, 0));
        btnApagar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnApagar.setText("Apagar LED");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnApagar);
        btnApagar.setBounds(285, 202, 113, 47);
        getContentPane().add(led3);
        led3.setBounds(621, 223, 61, 52);
        getContentPane().add(led1);
        led1.setBounds(621, 105, 61, 52);
        getContentPane().add(led2);
        led2.setBounds(621, 164, 61, 52);
        getContentPane().add(led4);
        led4.setBounds(621, 282, 61, 52);
        getContentPane().add(led6);
        led6.setBounds(621, 400, 61, 52);
        getContentPane().add(led5);
        led5.setBounds(621, 341, 61, 52);
        getContentPane().add(led7);
        led7.setBounds(621, 459, 61, 52);

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setText("Secuencia 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(285, 289, 113, 42);

        jButton2.setBackground(new java.awt.Color(153, 153, 0));
        jButton2.setText("Secuencia 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(285, 344, 113, 42);

        jButton3.setBackground(new java.awt.Color(153, 153, 0));
        jButton3.setText("Secuencia 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(285, 399, 113, 42);

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Detener");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(285, 448, 113, 42);

        jSlider1.setBackground(new java.awt.Color(102, 102, 102));
        jSlider1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSlider1.setForeground(new java.awt.Color(102, 255, 0));
        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMaximum(634);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(10);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1);
        jSlider1.setBounds(770, 70, 100, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/fondo2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConectarActionPerformed
        // TODO add your handling code here:
        conectar();
    }//GEN-LAST:event_bntConectarActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // TODO add your handling code here:
        desconectar();
    }//GEN-LAST:event_btnDesconectarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if (puertoUSB.isConnected()) {
            desconectar();
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnLed5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed5ActionPerformed
        // TODO add your handling code here:
        enviarDato(9);
        prenderLed(led5);
    }//GEN-LAST:event_btnLed5ActionPerformed

    private void btnLed6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed6ActionPerformed
        // TODO add your handling code here:
        enviarDato(10);
        prenderLed(led6);
    }//GEN-LAST:event_btnLed6ActionPerformed

    private void bntLed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLed1ActionPerformed
        // TODO add your handling code here:
        enviarDato(5);
        prenderLed(led1);
    }//GEN-LAST:event_bntLed1ActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        enviarDato(19);
        cargarImagenes();
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnLed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed2ActionPerformed
        // TODO add your handling code here:
        enviarDato(6);
        prenderLed(led2);
    }//GEN-LAST:event_btnLed2ActionPerformed

    private void btnLed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed3ActionPerformed
        // TODO add your handling code here:
        enviarDato(7);
        prenderLed(led3);
    }//GEN-LAST:event_btnLed3ActionPerformed

    private void btnLed4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed4ActionPerformed
        // TODO add your handling code here:
        enviarDato(8);
        prenderLed(led4);
    }//GEN-LAST:event_btnLed4ActionPerformed

    private void btnLed7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLed7ActionPerformed
        // TODO add your handling code here:
        enviarDato(11);
        prenderLed(led7);
    }//GEN-LAST:event_btnLed7ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        valorPot=jSlider1.getValue();
        if(valorPot<200 && valorPot>0){
            enviarDato(60);
        }
        if(valorPot<400 && valorPot>201){
           enviarDato(61); 
        }
        if(valorPot<600 && valorPot>401){
             enviarDato(62); 
        }
        if(valorPot>601){
             enviarDato(63); 
        }
        
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         enviarDato(55);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         enviarDato(56);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         enviarDato(57);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         enviarDato(58);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConectar;
    private javax.swing.JButton bntLed1;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnLed2;
    private javax.swing.JButton btnLed3;
    private javax.swing.JButton btnLed4;
    private javax.swing.JButton btnLed5;
    private javax.swing.JButton btnLed6;
    private javax.swing.JButton btnLed7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel led1;
    private javax.swing.JLabel led2;
    private javax.swing.JLabel led3;
    private javax.swing.JLabel led4;
    private javax.swing.JLabel led5;
    private javax.swing.JLabel led6;
    private javax.swing.JLabel led7;
    private javax.swing.JLabel txtEstado;
    // End of variables declaration//GEN-END:variables

    @Override
    public void serialEvent(SerialPortEvent evento) {
        try {
            if (evento.getEventType() == SerialPortEvent.DATA_AVAILABLE) {
                DataInputStream lectura = new DataInputStream(puertoUSB.getInputStream());
                if (lectura.available() > 0) {
                    int valor = lectura.read();
                    //System.out.println(valor);
                    controlLeds(valor);
                    if (valor == 50) {
                        cargarImagenes();                        
                        //JOptionPane.showMessageDialog(this, "Hay una peticion desde arduino");
                    }
                   

                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
